schema_version = "1.0.0"
id = "spreadsheet"
version = "1.0.0"
name = "Spreadsheet"
tagline = "Attribut spreadsheet"
maintainer = "Blender Bob"
type = "add-on"
website = "https://github.com/riouxr/Spreadsheet"
tags = ["Mesh", "Animation"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]
copyright = ["2025 Robert Rioux"]